---
version: '3.7'
services:
  cicd-app1-web:
    image: makwanji/cicd-app1-web:latest
    container_name: cicd-app1-web
    ports:
      - 480:80
  cicd-app1-app:
    image: makwanji/cicd-app1-app:latest
    container_name: cicd-app1-app
    ports:
      - 48080:8080
  cicd-app1-db:
    image: makwanji/cicd-app1-db:latest
    container_name: cicd-app1-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 43306:3306
    volumes:
      - cicd-app1-db-data:/var/lib/mysql
volumes:
  cicd-app1-db-data:
networks:
  default:
    external: true
    name: cicd
