version: "3.7"
services:
  cicd-app1-uat-db:
    image: 'makwanji/cicd-app1-db:uat-latest'
    restart: always
    container_name: 'cicd-app1-uat-db'
    hostname: 'cicd-app1-uat-db'
    env_file: ./config/app1-uat-db.env
    ports:
      - '3306'
    volumes:
      - mysql-uat-data:/var/lib/mysql
  cicd-app1-uat-app:
    image: 'makwanji/cicd-app1-app:uat-latest'
    restart: always
    container_name: 'cicd-app1-uat-app'
    hostname: 'cicd-app1-uat-app'
    env_file: ./config/app1-uat-app.env
    depends_on:
      - cicd-app1-uat-db
    ports:
      - '80'
  cicd-app1-uat-web:
    image: 'makwanji/cicd-app1-web:uat-latest'
    restart: always
    container_name: 'cicd-app1-uat-web'
    hostname: 'cicd-app1-uat-web'
    env_file: ./config/app1-uat-web.env
    depends_on:
      - cicd-app1-uat-db
      - cicd-app1-uat-app
    ports:
      - '380:80'
volumes:
  mysql-uat-data:
networks:
  default:
      external: true
      name: cicd-app1
