version: "3.7"
services:
  cicd-app1-dev-db:
    image: 'cicd-app1-db'
    restart: always
    container_name: 'cicd-app1-dev-db'
    hostname: 'cicd-app1-dev-db'
    env_file: ./config/app1-dev-web.env
    ports:
      - '3306'
    volumes:
      - mysql-dev-data:/var/lib/mysql
  cicd-app1-dev-app:
    image: 'rts-app:1.0'
    restart: always
    container_name: 'cicd-app1-dev-app'
    hostname: 'cicd-app1-dev-app'
    env_file: ./config/app1-dev-app.env
    depends_on:
      - cicd-app1-dev-db
    ports:
      - '80'
  cicd-app1-dev-web:
    image: 'rts-web:1.0'
    restart: always
    container_name: 'cicd-app1-dev-web'
    hostname: 'cicd-app1-dev-web'
    env_file: ./config/app1-dev-web.env
    depends_on:
      - cicd-app1-dev-db
      - cicd-app1-dev-app
    ports:
      - '180:80'
volumes:
  mysql-dev-data:
networks:
  default:
      external: true
      name: cicd-app1
