version: "3.7"
services:
  cicd-app1-sit-db:
    image: 'makwanji/cicd-app1-db:sit-latest'
    restart: always
    container_name: 'cicd-app1-sit-db'
    hostname: 'cicd-app1-sit-db'
    env_file: ./config/app1-sit-web.env
    ports:
      - '3306'
    volumes:
      - mysql-sit-data:/var/lib/mysql
  cicd-app1-sit-app:
    image: 'makwanji/cicd-app1-app:sit-latest'
    restart: always
    container_name: 'cicd-app1-sit-app'
    hostname: 'cicd-app1-sit-app'
    env_file: ./config/app1-sit-app.env
    depends_on:
      - cicd-app1-sit-db
    ports:
      - '80'
  cicd-app1-sit-web:
    image: 'makwanji/cicd-app1-web:sit-latest'
    restart: always
    container_name: 'cicd-app1-sit-web'
    hostname: 'cicd-app1-sit-web'
    env_file: ./config/app1-sit-web.env
    depends_on:
      - cicd-app1-sit-db
      - cicd-app1-sit-app
    ports:
      - '280:80'
volumes:
  mysql-sit-data:
networks:
  default:
      external: true
      name: cicd-app1

