---
version: '3.7'
services:
  cicd-app1-sit-web:
    image: nginx
    container_name: cicd-app1-sit-web
    ports:
      - 280:80
  cicd-app1-sit-app:
    image: nginx
    container_name: cicd-app1-sit-app
    ports:
      - 28080:8080
  cicd-app1-sit-db:
    image: makwanji/cicd-app1-db:sit-latest
    container_name: cicd-app1-sit-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 23306:3306
    volumes:
      - cicd-app1-sit-db-data:/var/lib/mysql
volumes:
  cicd-app1-sit-db-data:
networks:
  default:
    external: true
    name: cicd-app1-sit
