version: "3.7"
services:
  cicd-app1-prod-db:
    image: 'cicd-app1-db'
    restart: always
    container_name: 'cicd-app1-prod-db'
    hostname: 'cicd-app1-prod-db'
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - '3306'
    volumes:
      - mysql-prod-data:/var/lib/mysql
  cicd-app1-prod-app:
    image: 'rts-app:1.0'
    restart: always
    container_name: 'cicd-app1-prod-app'
    hostname: 'cicd-app1-prod-app'
    env_file: ./config/app1-prod-app.env
    depends_on:
      - cicd-app1-prod-db
    ports:
      - '80'
  cicd-app1-prod-web:
    image: 'rts-web:1.0'
    restart: always
    container_name: 'cicd-app1-prod-web'
    hostname: 'cicd-app1-prod-web'
    env_file: ./config/app1-dev-web.env
    depends_on:
      - cicd-app1-prod-db
      - cicd-app1-prod-app
    ports:
      - '480:80'
volumes:
  mysql-prod-data:
networks:
  default:
      external: true
      name: cicd-app1
