---
version: '3.7'
services:
  cicd-app1-uat-web:
    image: makwanji/cicd-app1-web:uat-latest
    container_name: cicd-app1-uat-web
    ports:
      - 380:80
  cicd-app1-uat-app:
    image: makwanji/cicd-app1-app:uat-latest
    container_name: cicd-app1-uat-app
    ports:
      - 38080:8080
  cicd-app1-uat-db:
    image: makwanji/cicd-app1-db:uat-latest
    container_name: cicd-app1-uat-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 33306:3306
    volumes:
      - cicd-app1-uat-db-data:/var/lib/mysql
volumes:
  cicd-app1-uat-db-data:
networks:
  default:
    external: true
    name: cicd
