version: "3.7"
services:
  cicd-app1-uat-db:
    image: 'cicd-app1-db'
    restart: always
    container_name: 'cicd-app1-uat-db'
    hostname: 'cicd-app1-uat-db'
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - '3306'
    volumes:
      - mysql-uat-data:/var/lib/mysql
  cicd-app1-uat-app:
    image: 'rts-app:1.0'
    restart: always
    container_name: 'cicd-app1-uat-app'
    hostname: 'cicd-app1-uat-app'
    environment:
      DB_CONNECTION: 'mysql'
      DB_HOST: 'cicd-app1-uat-db'
      DB_PORT: '3306'
      DB_DATABASE: 'music'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'supersecret'
    depends_on:
      - cicd-app1-uat-db
    ports:
      - '80'
  cicd-app1-uat-web:
    image: 'rts-web:1.0'
    restart: always
    container_name: 'cicd-app1-uat-web'
    hostname: 'cicd-app1-uat-web'
    environment:
      API_URL: 'http://cicd-app1-uat-app'
      APP_ENV: UAT
    depends_on:
      - cicd-app1-uat-db
      - cicd-app1-uat-app
    ports:
      - '380:80'
volumes:
  mysql-uat-data:
networks:
  default:
      external: true
      name: cicd-app1
