---
version: '3.7'
services:
  cicd-app1-db:
    image: makwanji/cicd-app1-db:dev-latest
    container_name: cicd-app1-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 13306:3306
    volumes:
      - cicd-app1-dev-db-data:/var/lib/mysql
volumes:
  cicd-app1-dev-db-data:
networks:
  default:
    external: true
    name: cicd-app1-dev
